################################################################################  
#Sources:
#https://rawcdn.githack.com/constantAmateur/SoupX/204b602418df12e9fdb4b68775a8b486c6504fe4/inst/doc/pbmcTutorial.html
#https://www.science.org/doi/10.1126/science.aax1971

#Load Libraries:
LIB='/cluster/tufts/hpc/tools/R/4.0.0'
.libPaths(c("/tmp/RtmpUEJctP/downloaded_packages",LIB))
.libPaths()

library(SoupX)
library(reticulate)
library(Seurat)
library(sctransform)
library(ggplot2)
library(plotly)
library(tidyr)
library(dplyr)
library(cowplot)
library(BiocManager)
library(Matrix)
library(SoupX)


#Set Working Directory: 
setwd("/cluster/tufts/chinlab/gperer01/to_send/Liam/V2/0_SoupX")
################################################################################

################################################################################
#Load Data: Table of Cells(TOC) and Table of Droplets(TOD)
toc = Seurat::Read10X(data.dir = "/cluster/tufts/chinlab/single_nuclei_taz_mice/TAZ_MICE_COUNT_MATRICES/mouse_4685_counts/outs/filtered_feature_bc_matrix")
tod = Seurat::Read10X(data.dir = "/cluster/tufts/chinlab/single_nuclei_taz_mice/TAZ_MICE_COUNT_MATRICES/mouse_4685_counts/outs/raw_feature_bc_matrix")

dim(toc)
dim(tod)

#Create Soup Channel Object
sc = SoupChannel(tod = tod, toc = toc, calcSoupProfile = FALSE)

#Estimated Profile of Soup from Droplets with 2-10 UMIs
sc = estimateSoup(sc, soupRange = c(2,10), keepDroplets = FALSE) 

#Add Meta Data to Soup Channel Object: 
#Provide Clustering Data Generated by CellRanger
clusters<-read.csv(file = "/cluster/tufts/chinlab/single_nuclei_taz_mice/TAZ_MICE_COUNT_MATRICES/mouse_4685_counts/outs/analysis/clustering/graphclust/clusters.csv")
sc = setClusters(sc, setNames(clusters$Cluster, clusters$Barcode))

#Provide Dimension Reduction(UMAP) Data Generated by CellRanger
dimension_reduction<-read.csv(file = "/cluster/tufts/chinlab/single_nuclei_taz_mice/TAZ_MICE_COUNT_MATRICES/mouse_4685_counts/outs/analysis/umap/2_components/projection.csv")
metadata<-cbind(clusters,dimension_reduction[,2:3])
rownames(metadata)<-metadata[,1]
metadata<-metadata[,2:4]
sc = setDR(sc, metadata[,2:3]) #manually specify dimension reduction in soup channel object
################################################################################

################################################################################
#Sanity Check Visualizations: 
#UMAP Plot: 
dd = metadata
plot = dd %>%ggplot(aes(x = UMAP.1, y = UMAP.2, color = factor(Cluster),))+
  geom_point() + labs(x = "UMAP1", y = "UMAP2", subtitle = "SoupX m4685: UMAP Plot ")
plot
ggsave("images/m4685_SoupXPlot_UMAP.png")

#Plot Cells with Mybpc3 Expression
#Mybpc3 expression chosen because CM markers have been strong source of contamination in other datasets
dd$Mybpc3 = sc$toc["Mybpc3", ]
gg = ggplot(dd, aes(UMAP.1, UMAP.2)) + geom_point(aes(colour = Mybpc3 > 0)) + labs(x = "UMAP1", y = "UMAP2", subtitle = "SoupX m4685: Cells with Mybpc3 Expression ")
plot(gg)
ggsave(filename = "images/m4685_SoupXPlot_UMAP_Mybpc3.png")

#Plot Cells with Mybpc3 Expression >than Expected # of Counts than if Cell Contained Nothing but Soup(Ratio: Observed/Expected):  
gg = plotMarkerMap(sc, "Mybpc3") + labs(x = "UMAP1", y = "UMAP2", subtitle = "SoupX m4685: Cells with Mybpc3 Expression Enriched Over Background (Observed/Expected)")
plot(gg)
ggsave(filename = "images/m4685_SoupXPlot_UMAP_Mybpc3_Observed.Expected.Ratio.png")

#Estimate Contamination Fraction and Correct Count Matrix
sc = autoEstCont(sc)

#Add 0.2 to Contamination Fraction
contamination_faction<-sc[["metaData"]][["rho"]][1]+ 0.2
contamination_faction<-round(contamination_faction, digits = 2)
################################################################################

################################################################################
#Add 0.2 to Remove 99% Soup
sc = setContaminationFraction(sc, contamination_faction)

#Correct Expression Profile
out = adjustCounts(sc, roundToInt=TRUE)
saveRDS(out, file = "out/m4685_SoupXObject_Corrected_Matrix.rds" )
################################################################################

################################################################################
#Plot Fraction of Mybpc3 Expression Determined to be Soup 
plotChangeMap(sc, out, "Mybpc3")+labs(subtitle = "m4685")
ggsave("images/m4685_SoupXPlot_Mybpc3.Soup.Correction.png")

#print contamination fraction and number of barcodes in toc/tod
dim(toc)[2]
dim(tod)[2]
contamination_faction

#see warnings
warnings()
################################################################################